#!/usr/bin/env python3
"""Regenerate the Docker dependency locks from authoritative declarations.

The refresh is deliberately NOT circular:

* The Docker ``resolve`` stage only materializes the runtime dependency
  declarations from pyproject.toml into deps.txt; it installs nothing and never
  reads docker/requirements.lock (the locks can even be absent).
* This script performs the single authoritative dependency resolution per
  supported platform: one ``pip download --only-binary=:all:`` run per
  platform, whose exact artifacts are then hashed into the lock. There is no
  other resolver execution for the runtime graph anywhere in the image build.
* Per-platform records must be structurally identical — the same canonical
  distribution names and the same versions on every platform, differing only
  in the SHA-256 artifact sets (binary wheels differ per platform). Otherwise
  the generator aborts instead of merging graphs that the unconditional lock
  format would misrepresent.
* The build toolchain lock (docker/build-requirements.lock) is regenerated from
  the approved tool versions in BUILD_TOOL_PINS the same way.

Usage: python scripts/refresh_docker_lock.py

Prerequisites: Docker with BuildKit; a Python environment with the ``packaging``
library (satisfied by the project's ``dev`` extra).
"""

from __future__ import annotations

import hashlib
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name, parse_wheel_filename

ROOT = Path(__file__).resolve().parents[1]

# The only Docker platforms supported and validated by the project. Adding a
# platform means adding it here, validating the build end to end, and merging
# its artifact hashes into the locks by re-running this script.
SUPPORTED_PLATFORMS = ("linux/amd64", "linux/arm64")

# Approved build-toolchain versions, observed against the pinned base image.
# Bumping a tool version is an intentional change: update this mapping and
# re-run this script so the new artifacts are hash-checked into the lock.
BUILD_TOOL_PINS = {
    "build": "1.5.0",
    "packaging": "26.3",
    "pyproject-hooks": "1.2.0",
    "setuptools": "84.0.0",
}

_RUNTIME_HEADER = """\
# Docker runtime dependency lock for PermitDiff.
#
# Exact-version pins with SHA-256 hashes for the supported platforms documented
# in docs/docker-reproducibility.md. Multiple --hash entries per distribution
# authorize the platform-specific binary wheels (for example pydantic-core,
# PyYAML) under one committed lock.
#
# Generated by scripts/refresh_docker_lock.py from the pyproject.toml
# [project].dependencies declarations on the base image digest pinned in the
# Dockerfile. The deterministic final image installs this file with
# --require-hashes and --only-binary=:all:, so any missing, unknown, or
# tampered artifact fails the Docker build.
#
# Do not edit by hand. Refresh procedure: docs/docker-reproducibility.md.
"""

_BUILD_TOOLS_HEADER = """\
# Docker build toolchain lock for PermitDiff.
#
# Exact-version pins with SHA-256 hashes for the approved build toolchain
# (build frontend, packaging, pyproject_hooks, setuptools). Installed in the
# Docker build stage with --require-hashes and --only-binary=:all:, and the
# wheel is built with --no-isolation so the hash-verified toolchain cannot be
# bypassed by pip's isolated build environment.
#
# Approved versions live in BUILD_TOOL_PINS of scripts/refresh_docker_lock.py.
# Do not edit by hand. Refresh procedure: docs/docker-reproducibility.md.
"""


def _docker() -> str:
    path = shutil.which("docker")
    if path is None:
        raise SystemExit("docker executable not found on PATH")
    return path


def hash_wheel_dir(directory: Path) -> dict[str, dict[str, set[str]]]:
    """Map canonical distribution name -> version -> set of SHA-256 digests."""
    records: dict[str, dict[str, set[str]]] = {}
    for wheel in directory.glob("*.whl"):
        name, version, _build, _tags = parse_wheel_filename(wheel.name)
        digest = hashlib.sha256(wheel.read_bytes()).hexdigest()
        records.setdefault(name, {}).setdefault(str(version), set()).add(digest)
    return records


def merge_records(
    per_platform: list[dict[str, dict[str, set[str]]]],
    platforms: tuple[str, ...] = SUPPORTED_PLATFORMS,
) -> dict[str, dict[str, set[str]]]:
    """Merge per-platform artifact records into one unconditional lock.

    The committed lock format carries no platform markers, so every supported
    platform must resolve the identical canonical distribution-name set and
    identical versions for each distribution; only the SHA-256 artifact sets
    may differ per platform. Aborts with a diagnostic naming the platform and
    the offending names/versions instead of silently merging incompatible
    graphs.
    """
    if len(platforms) != len(per_platform):
        raise SystemExit(f"record count {len(per_platform)} does not match platforms {platforms}")
    all_names = set().union(*(set(records) for records in per_platform))
    for index, records in enumerate(per_platform):
        missing = all_names - set(records)
        if missing:
            raise SystemExit(
                f"platform {platforms[index]} dependency set differs: missing {sorted(missing)}"
            )
    merged: dict[str, dict[str, set[str]]] = {}
    for records in per_platform:
        for name, versions in records.items():
            for version, digests in versions.items():
                existing = merged.setdefault(name, {})
                if version not in existing and existing:
                    raise SystemExit(
                        f"platform version mismatch for {name}: {sorted(existing)} vs {version}"
                    )
                existing.setdefault(version, set()).update(digests)
    return merged


def render_lock(pins: dict[str, dict[str, set[str]]], header: str) -> str:
    """Render one hash-checkedrequirements file, sorted for determinism."""
    lines = [header]
    for name in sorted(pins):
        versions = pins[name]
        (version,) = versions
        digests = sorted(versions[version])
        if any(len(digest) != 64 for digest in digests):
            raise SystemExit(f"non-SHA-256 digest recorded for {name}")
        hashes = " ".join(f"--hash=sha256:{digest}" for digest in digests)
        lines.append(f"{name}=={version} {hashes}")
    return "\n".join(lines) + "\n"


def write_lock(path: Path, content: str) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)


def declared_dependencies() -> list[Requirement]:
    pyproject = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    return [Requirement(raw) for raw in pyproject["project"]["dependencies"]]


def run(command: list[str]) -> None:
    result = subprocess.run(command, check=False, capture_output=True, text=True)
    if result.returncode != 0:
        sys.stderr.write(result.stdout)
        sys.stderr.write(result.stderr)
        raise SystemExit(f"command failed with exit {result.returncode}: {' '.join(command)}")


def main() -> None:
    docker = _docker()
    runtime_platform_records: list[dict[str, dict[str, set[str]]]] = []
    tools_platform_records: list[dict[str, dict[str, set[str]]]] = []

    with tempfile.TemporaryDirectory(prefix="permitdiff-lock-") as workspace:
        for platform in SUPPORTED_PLATFORMS:
            tag = platform.replace("/", "-")
            image = f"permitdiff:resolve-{tag}"
            run(
                [
                    docker,
                    "build",
                    "--no-cache",
                    "--platform",
                    platform,
                    "--target",
                    "resolve",
                    "-t",
                    image,
                    str(ROOT),
                ]
            )
            runtime_dir = Path(workspace) / tag / "runtime"
            tools_dir = Path(workspace) / tag / "tools"
            runtime_dir.mkdir(parents=True)
            tools_dir.mkdir(parents=True)
            # Single authoritative runtime resolution per platform: pip download
            # resolves the declared graph, and exactly these artifacts are
            # hashed into docker/requirements.lock.
            run(
                [
                    docker,
                    "run",
                    "--rm",
                    "--platform",
                    platform,
                    "-v",
                    f"{runtime_dir}:/wheels/runtime",
                    "--entrypoint",
                    "/usr/local/bin/python",
                    image,
                    "-m",
                    "pip",
                    "download",
                    "--no-cache-dir",
                    "--only-binary=:all:",
                    "-r",
                    "/resolve/deps.txt",
                    "-d",
                    "/wheels/runtime",
                ]
            )
            tool_pins = [f"{name}=={version}" for name, version in sorted(BUILD_TOOL_PINS.items())]
            run(
                [
                    docker,
                    "run",
                    "--rm",
                    "--platform",
                    platform,
                    "-v",
                    f"{tools_dir}:/wheels/tools",
                    "--entrypoint",
                    "/usr/local/bin/python",
                    image,
                    "-m",
                    "pip",
                    "download",
                    "--no-cache-dir",
                    "--only-binary=:all:",
                    "--no-deps",
                    *tool_pins,
                    "-d",
                    "/wheels/tools",
                ]
            )
            runtime_platform_records.append(hash_wheel_dir(runtime_dir))
            tools_platform_records.append(hash_wheel_dir(tools_dir))

    runtime_pins = merge_records(runtime_platform_records)
    tools_pins = merge_records(tools_platform_records)

    for requirement in declared_dependencies():
        name = canonicalize_name(requirement.name)
        if name not in runtime_pins:
            raise SystemExit(f"declared dependency {name} missing from resolved lock")
        (version,) = runtime_pins[name]
        if not requirement.specifier.contains(version, prereleases=True):
            raise SystemExit(
                f"{name} resolved to {version}, outside declared {requirement.specifier}"
            )

    for name, version in BUILD_TOOL_PINS.items():
        pinned = tools_pins.get(name)
        if pinned is None or version not in pinned:
            raise SystemExit(f"build tool {name} not resolved to approved version {version}")

    write_lock(ROOT / "docker" / "requirements.lock", render_lock(runtime_pins, _RUNTIME_HEADER))
    write_lock(
        ROOT / "docker" / "build-requirements.lock",
        render_lock(tools_pins, _BUILD_TOOLS_HEADER),
    )
    print(
        f"wrote docker/requirements.lock ({len(runtime_pins)} distributions, {SUPPORTED_PLATFORMS})"
    )
    print(f"wrote docker/build-requirements.lock ({len(tools_pins)} distributions)")


if __name__ == "__main__":
    main()
